# Name of your application. Used to uniquely configure containers.
service: turbo-laravel-site

# Name of the container image.
image: turbo-laravel/site

env:
  clear:
    APP_NAME: "Turbo Laravel"
    APP_ENV: "production"
    APP_DEBUG: false
    APP_URL: "https://turbo-laravel.com"
    ASSET_URL: "https://turbo-laravel.com"
    LOG_CHANNEL: "stderr"
    LOG_DEPRECATIONS_CHANNEL: "null"
    LOG_LEVEL: "debug"
    MAIL_MAILER: "log"
    BROADCAST_DRIVER: "log"
    FILESYSTEM_DISK: "local"
    QUEUE_CONNECTION: "sync"
    SESSION_DRIVER: "file"
    SESSION_LIFETIME: "120"
  secret:
    - APP_KEY
    - TORCHLIGHT_TOKEN

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: registry.digitalocean.com
  username:
    - KAMAL_REGISTRY_USERNAME

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  multiarch: false

healthcheck:
  path: /up
  port: 8080

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /var/www/html/public/dist

traefik:
  host_port: 8080

